// Site content, hand-authored. Every view (terminal, Easy Mode, virtual FS) reads from here,
// so adding a project or changing a label only touches this file.

window.SITE_DATA = {
  // Central site-level constants - edit here, no other file needs to change.
  // (index.html <title>/<meta> is static and must be updated separately.)
  site: {
    handle: "99jik",                                 // shell prompt host, storage key prefix
    domain: "99jik.com",                             // user-facing canonical domain
    github: "99jik",                                 // github.com/<this> for project repos
    til: "til.99jik.com",                            // short TIL label
    tilUrl: "https://til.99jik.com",                 // full TIL URL
    cvKo: "https://github.com/99JIK/cv/blob/main/cv-ko.pdf",  // CV (ko), hosted in the cv repo
    cvEn: "https://github.com/99JIK/cv/blob/main/cv-en.pdf",  // CV (en), hosted in the cv repo
    // Footer (c) year and the "updated" date come from __BUILD_DATE__, injected by
    // scripts/build.mjs. Hand-written dates rot: the old updatedLabel sat 4 months stale.
    // Public iCal feed. Not a secret: anyone can already read this calendar, which
    // is why it lives here instead of in a repo secret that can quietly expire.
    // No CORS headers on Google's side, so the browser cannot fetch it directly.
    // Only scripts/fetch-calendar.mjs uses it, to refresh the fallback snapshot
    // during deploy; the page itself reads the Calendar API below.
    icalUrl: "https://calendar.google.com/calendar/ical/99jik%4099jik.com/public/basic.ics",
    calendarId: "99jik@99jik.com",
    // Browser API key: the calendar is read live and nothing needs syncing. An empty
    // string falls back to the committed public/calendar.json snapshot, and so does a
    // failed request, so a bad key or a quota problem never empties the calendar.
    //
    // The key is public by design (it ships in the bundle). Its only protection is the
    // HTTP referrer restriction set in Google Cloud, so that restriction is not
    // optional. A referrer-restricted key also fails from localhost unless localhost
    // is on the allow list, which just means local dev reads the snapshot.
    gcalApiKey: "AIzaSyCTq5wjQREru3sWUbGXvyiFPM4JhRs847Y",
    bookingUrl: "https://calendar.app.google/ApbFL4J7C88LE2YQ7",  // "book a slot" page
    // /home/jeongin/.midnight/playlist.m3u, read live from the YouTube Data API.
    // Needs that API enabled on the same Google Cloud project as gcalApiKey, and the
    // key's API restrictions widened to include it. Empty string leaves the file empty.
    //
    // A YouTube Music playlist works too, as long as you made it and it is public or
    // unlisted: it is the same PL... id. Auto-generated ones do not: liked music (LM),
    // mixes and radio (RD...) are not exposed to the Data API at all. A VL prefix from
    // a library link is stripped automatically.
    youtubePlaylistId: "PLf_GfOjs8pH-AQnIw50e4SaJv1Lle8qwh",
    gaTagId: "G-4MY31MY2XZ",                          // GA4 measurement ID (empty string disables)
  },

  profile: {
    name_en: "Jeongin Kim",
    name_ko: "김정인",
    role_en: "MS Candidate · Software Testing Lab",
    role_ko: "석사과정 · 소프트웨어 테스팅 연구실",
    affiliation_en: "Kyungpook National University",
    affiliation_ko: "경북대학교 컴퓨터학부",
    location_ko: "대구광역시, 대한민국",
    location_en: "Daegu, Republic of Korea",
    weatherLocation: "Daegu",                        // wttr.in query, used by `weather` and the dock
    email: "99jik@99jik.com",
    github: "99jik",
    linkedin: "jeongin-kim-74ba69384",
    scholar: null,
    til: "https://til.99jik.com",
  },

  // The CV's research interests, in its own order: software testing, LLM-based test
  // generation, SIL verification environments, predictive modelling on industrial
  // process data. The old SLM card was not in the CV and is gone.
  research: [
    { tag: "LLM",  title_en: "LLM-based test generation",   title_ko: "LLM 기반 테스트 생성",
      blurb_ko: "대규모 언어모델로 테스트와 시험 환경의 거동을 생성",
      blurb_en: "Generating tests, and the behaviour of the environment they run in, with large language models." },
    { tag: "SIL",  title_en: "SIL verification environments", title_ko: "SIL 검증 환경",
      blurb_ko: "하드웨어 없이 제어/임베디드 로직을 루프에서 검증하는 환경을 더 싸게 구축",
      blurb_en: "Building software-in-the-loop verification environments, and building them at lower cost." },
    { tag: "IND",  title_en: "Predictive modelling on process data", title_ko: "산업 공정 데이터 예측 모델링",
      blurb_ko: "제조 공정 데이터에서 품질을 예측. 시간 배치 효과를 잠재변수로 다룸",
      blurb_en: "Predicting quality from manufacturing process data, treating temporal batch effects as a latent variable." },
  ],

  // Each entry also becomes <slug>.md in the virtual FS (see fs.js).
  // `url` is where the Easy Mode card links; defaults to the GitHub repo when omitted.
  // `summary_*` is the one line the table and the cards show; `detail_*` is what the
  // CV says, and only `cat <slug>` and the .md file go that deep.
  projects: [
    { slug: "KCC2026", title_en: "LLM-generated test environment behaviours", title_ko: "LLM 기반 시험 환경 거동 생성",
      year: 2026, featured: true, stack: ["Python", "C++", "LLM", "Behaviour Trees"],
      summary_en: "Generating the behaviour of environment objects for SIL testing with an LLM, through a three-stage prompt pipeline.",
      summary_ko: "SIL 테스팅에서 환경 객체의 거동을 LLM으로 생성. 3단계 프롬프트 파이프라인.",
      detail_en: [
        "Decomposition, induction and synthesis as three prompt stages rather than one.",
        "More than doubled coverage over zero-shot and few-shot baselines across 11 objects in three domains: elevator, drone, smart factory.",
        "Consistent on both GPT-4 and Llama-3 70B, so the gain is in the pipeline rather than in one model.",
        "Published at KCC 2026.",
      ],
      detail_ko: [
        "한 번의 프롬프트가 아니라 분해, 귀납, 합성의 3단계로 나눠 생성.",
        "엘리베이터, 드론, 스마트팩토리 3개 도메인 11개 객체에서 zero-shot 및 few-shot 대비 커버리지 2배 이상.",
        "GPT-4와 Llama-3 70B 양쪽에서 일관. 특정 모델이 아니라 파이프라인의 효과.",
        "KCC 2026 게재.",
      ] },

    { slug: "ABB", title_en: "Real-time facial emotion classification", title_ko: "실시간 표정 감정 분류",
      year: 2026, featured: true, stack: ["Python", "MediaPipe", "TensorFlow", "FastAPI"],
      summary_en: "Emotion classification from facial action units, light enough to run on an edge device. Industry work with Y Design Lab.",
      summary_ko: "얼굴 액션 유닛으로 감정을 분류. 엣지 디바이스에서 돌아갈 만큼 경량. (주)와이디자인랩 산학 과제.",
      detail_en: [
        "Built to run on an edge device rather than a server, so the model is kept small enough to stay real time there.",
        "Up to 30 faces at once, with IoU-based multi-face tracking.",
        "Event triggers on emotion changes and on action-unit thresholds, served over FastAPI REST and WebSocket streaming.",
        "Users label their own training data, with face angle taken into account, so accuracy improves on the faces and conditions that installation actually sees.",
      ],
      detail_ko: [
        "서버가 아니라 엣지 디바이스에서 도는 것이 전제. 그 위에서 실시간이 유지될 만큼 모델을 경량화.",
        "동시 30명까지, IoU 기반 다중 얼굴 트래킹.",
        "감정 변화와 액션 유닛 임계값에 이벤트 트리거. FastAPI REST와 WebSocket 스트리밍으로 제공.",
        "얼굴 각도 등을 고려해 사용자가 직접 학습 데이터를 라벨링. 실제 설치 환경의 얼굴과 조건에 맞춰 정확도를 올림.",
      ] },

    { slug: "ST_YOUNGWON", title_en: "Smart office RAG on a NAS", title_ko: "NAS 기반 사내 문서 RAG",
      year: 2026, featured: true, stack: ["FastAPI", "ChromaDB", "SQLite", "Docker"],
      summary_en: "Question answering over internal documents, running on the company NAS. Contract work, in production use.",
      summary_ko: "사내 문서 질의응답을 회사 NAS 위에서. (주)에스티영원 외주, 실제 운영 중.",
      detail_en: [
        "Regulatory documents chunked hierarchically by article, paragraph and fixed size, then retrieved by hybrid keyword and vector search.",
        "OpenAI, Claude, Gemini and local Ollama sit behind one protocol abstraction so a provider can be swapped, which the client asked for as a maintainability requirement.",
        "Synology NAS integration through the FileStation API, JWT auth, deployed with Docker Compose.",
      ],
      detail_ko: [
        "규정 문서를 조, 항, 고정 크기의 계층으로 청킹하고 키워드와 벡터를 함께 쓰는 하이브리드 검색으로 회수.",
        "OpenAI, Claude, Gemini, 로컬 Ollama를 하나의 프로토콜 추상화 뒤에 둬서 교체 가능. 유지보수 요구사항으로 고객이 요청한 사항.",
        "Synology NAS를 FileStation API로 연동, JWT 인증, Docker Compose 배포.",
      ] },

    { slug: "COPY_JIKILLER", title_en: "AST-based plagiarism detector", title_ko: "AST 기반 표절 검사기",
      year: 2025, featured: true, stack: ["Python", "clang", "javalang"],
      summary_en: "Compares abstract syntax trees rather than text, so renaming and reformatting do not hide a copy.",
      summary_ko: "텍스트가 아니라 추상 구문 트리를 비교. 이름 바꾸기나 서식 변경으로는 숨겨지지 않음.",
      detail_en: [
        "Variable names and comments are ignored by construction, because they are not in the tree being compared.",
        "Python through the built-in ast module, C and C++ through clang, Java through javalang.",
        "Adjustable similarity threshold and a side-by-side diff viewer.",
        "Written for the programming exams I was assisting.",
      ],
      detail_ko: [
        "변수명과 주석은 비교 대상 트리에 없으므로 애초에 무시됨.",
        "Python은 내장 ast, C/C++은 clang, Java는 javalang으로 파싱.",
        "유사도 임계값 조절과 나란히 보기 diff 뷰어.",
        "조교로 들어간 프로그래밍 시험에 쓰려고 만듦.",
      ] },

    { slug: "FOCUS_KNU_2025_COMP0738", title_en: "FOCUS: concentration from webcam", title_ko: "FOCUS: 웹캠 기반 집중도 측정",
      year: 2025, featured: false, stack: ["JavaScript", "MediaPipe", "Vite"],
      summary_en: "Scores a learner's distraction in real time from five signals in webcam video. Team coursework project.",
      summary_ko: "웹캠 영상의 다섯 가지 신호로 학습자의 산만도를 실시간 산출. 팀 수업 프로젝트.",
      detail_en: [
        "The five signals: eye closure, head orientation, gaze with head-rotation compensation, yawning, and facial action units.",
        "Gaze is corrected for head rotation, so looking straight ahead with a turned head is not read as looking away.",
        "MediaPipe Face Landmarker, vanilla JS, Vite. Runs entirely in the browser.",
      ],
      detail_ko: [
        "다섯 신호: 눈 감김, 머리 방향, 머리 회전을 보정한 시선, 하품, 얼굴 액션 유닛.",
        "시선은 머리 회전을 보정. 고개를 돌린 채 정면을 보는 것을 딴 데 본다고 읽지 않음.",
        "MediaPipe Face Landmarker, 바닐라 JS, Vite. 전부 브라우저에서 동작.",
      ] },

    { slug: "DCU_AI_RECOMMENDED_SYSTEM", title_en: "Career guidance for students with disabilities", title_ko: "장애 학생 진로 추천",
      year: 2026, featured: false, stack: ["Python", "scikit-learn", "HTML"],
      summary_en: "Reads what a student with a disability has studied and recommends a career direction that fits it.",
      summary_ko: "장애 학생의 학습 내용을 보고 맞는 진로 방향을 추천.",
      detail_en: [],
      detail_ko: [] },

    { slug: "99JIK.com", title_en: "99jik.com", title_ko: "99jik.com",
      year: 2026, featured: false, stack: ["Preact", "esbuild", "GitHub Pages"],
      url: "https://github.com/99JIK/99JIK.com",
      summary_en: "This site: a portfolio shaped like a small operating system, with a shell, a window manager and a filesystem.",
      summary_ko: "이 사이트. 셸과 창 관리자와 파일시스템을 갖춘, 작은 운영체제 모양의 포트폴리오.",
      detail_en: [
        "No runtime framework beyond Preact, bundled by esbuild into one file and served from GitHub Pages.",
        "The calendar, the reading list, the repository list and the playlist are read live rather than copied in at build time.",
      ],
      detail_ko: [
        "Preact 외에 런타임 프레임워크 없음. esbuild로 한 파일로 묶어 GitHub Pages에서 서빙.",
        "일정, 읽은 글, 저장소 목록, 재생목록은 빌드 때 복사하지 않고 실시간으로 읽음.",
      ] },

    { slug: "til", title_en: "TIL(Today I Learned)", title_ko: "오늘 배운 것",
      year: 2025, featured: false, stack: ["Docusaurus", "MDX"], url: "https://til.99jik.com",
      summary_en: "Daily research and learning notes, deployed separately at til.99jik.com.",
      summary_ko: "쌓아가는 연구/학습 노트. til.99jik.com 에서 별도 운영.",
      detail_en: [],
      detail_ko: [] },
  ],

  // From the CV, which is the authoritative copy. All three are domestic conference
  // papers written in Korean, so the Korean title is the original and the English
  // one is the CV's translation. First author on all of them.
  publications: [
    { year: 2026, venue: "KCC 2026", pages: "582-584", role: "first author",
      title_ko: "대규모 언어 모델을 활용한 임베디드 소프트웨어 시험 환경의 행동 자동 생성",
      title_en: "Automatic Generation of Test Environment Behaviors Using LLM for Embedded Software Testing",
      where_ko: "한국정보과학회 학술발표논문집",
      authors: "김정인, 김덕엽, 서혜령, 이우진*",
      url: "https://github.com/99JIK/KCC2026" },
    { year: 2025, venue: "UCWIT 2025", role: "first author",
      title_ko: "생분해성 섬유 방사 공정의 성능 향상을 위한 샘플링 시점 데이터 활용 연구",
      title_en: "A Study on the Utilization of Sampling Time-point Data for Performance Enhancement of the Biodegradable Fiber Spinning Process",
      where_ko: "유비쿼터스 컴퓨팅 및 웹 정보기술 학술심포지엄, 한국정보과학회 영남지부",
      authors: "김정인, 이우진*" },
    { year: 2025, venue: "KCC 2025", pages: "397-399", role: "first author",
      title_ko: "생성형 AI의 테스트케이스 이해 및 활용 능력",
      title_en: "The Ability of Generative AI to Understand and Utilize Test Cases",
      where_ko: "한국정보과학회 학술발표논문집",
      authors: "김정인, 이우진*" },
  ],

  // Straight from the CV. The site used to say the MS began 2024.09 and the degree
  // was from KNU; both were wrong.
  experience: [
    { when: "2025.03 -",       what_ko: "석사과정, 컴퓨터학부",           what_en: "MS student, Computer Science and Engineering",
      where_ko: "경북대",       where_en: "KNU" },
    { when: "2024.12 -",       what_ko: "대학원 연구원, 소프트웨어 테스팅 연구실", what_en: "Graduate researcher, Software Testing Lab",
      where_ko: "경북대",       where_en: "KNU" },
    { when: "2025.03 -",       what_ko: "학부 조교",                      what_en: "Teaching assistant",
      where_ko: "경북대 컴퓨터학부", where_en: "KNU CSE" },
    { when: "2022.09 - 2024.06", what_ko: "연구원 (리버스 엔지니어링)",   what_en: "Researcher, reverse engineering",
      where_ko: "아크데이타",   where_en: "Arkdata" },
    { when: "2023.03 - 2024.02", what_ko: "학사, 컴퓨터정보공학 (전공심화)", what_en: "BEng, Computer Information Engineering",
      where_ko: "영진전문대",   where_en: "Yeungjin University" },
    { when: "2018.03 - 2023.02", what_ko: "전문학사, 컴퓨터정보계열",     what_en: "Associate degree, Computer Information",
      where_ko: "영진전문대",   where_en: "Yeungjin University" },
  ],

  // The CV's four rows. `research` used to claim fuzzing and the oracle problem, and
  // `tools` claimed LLVM and tree-sitter; none of the four appear in the CV or in any
  // public repository.
  skills: {
    languages: ["Python", "Java", "C/C++", "TypeScript", "JavaScript"],
    web: ["FastAPI", "Spring", "Node.js", "React", "Vue.js"],
    data: ["Oracle", "PostgreSQL", "MySQL", "ChromaDB", "scikit-learn", "LightGBM"],
    tools: ["Docker", "Git", "Linux", "Kafka"],
  },

  // Filed, not granted, and said that way. MOTIE/KIAT project P0022335.
  patents: [
    { year: 2026, status_ko: "가출원 완료, 정식 출원 진행 중", status_en: "provisional filed, full application in progress",
      title_ko: "강건한 최적 공정 파라미터 조합 선정 방법",
      title_en: "A Method for Selecting Robust Optimal Process Parameter Combinations",
      authors: "김정인, 김덕엽, 이우진",
      holder_ko: "경북대학교 산학협력단", holder_en: "KNU Industry-Academic Cooperation Foundation" },
  ],

  // "What I'm on lately" is not typed here any more: ~/now.log is generated from the
  // calendar, which is already the truth about where the time goes. The Easy Mode
  // section reads the same feed.

  // ── Notes that surface in the virtual filesystem ────────────────────────────
  // Everything below is yours to write. Empty arrays render as an empty file rather
  // than as invented content: a portfolio that makes up research notes is worse than
  // one with none.
  notes: {
    // Each entry becomes one file under /home/memo/. Split by domain, because a
    // simulator gotcha and something learned on the job do not belong in the same
    // file. `file` is the filename, `title` is the heading, `notes` are the lines.
    //
    //   { file: "carla.md", title: "CARLA",
    //     notes: ["동기 모드에서 tick 안 부르면 센서 콜백이 안 옴"] }
    memo: [],

    // /home/jeongin/.lab/principles.md -- what stays true when the topic changes.
    // Written as markdown because it is a document, not a list: the Files window and
    // the viewer render it, and `cat` still prints the source.
    principles: [
      "# 연구 일반 원칙",
      "",
      "분야와 주제가 바뀌어도 남는 것들. 실행 단계의 위생이 체크리스트라면,",
      "이건 그 위층이다.",
      "",
      "## 1. 문제 고르기",
      "",
      "- **좋은 문제의 조건은 셋이다**: 답이 나오면 누군가 행동을 바꾼다 / 내가 답할 수단이 있다 / 아직 답이 없다. 하나라도 빠지면 다시 고른다.",
      "- \"아무도 안 했다\"는 이유만으로 하지 않는다. 안 한 데는 대개 이유가 있고, 그 이유가 뭔지 먼저 찾는다. 이유가 \"가치가 없어서\"인지 \"어려워서\"인지가 갈림길이다.",
      "- 문제를 고르는 시간은 아깝지 않다. 잘못된 문제를 6개월 잘 푸는 것보다 옳은 문제를 2주 고르는 게 싸다.",
      "- **측정할 수 있는 형태로 좁혀질 때까지는 아직 연구 질문이 아니다.** \"X가 더 나은가\"는 질문이 아니다. \"어떤 조건에서, 무엇으로 재서, 얼마나\"가 붙어야 한다.",
      "- 기여를 한 문장으로 못 쓰면 아직 기여가 없다. 그 문장을 먼저 쓰고 실험을 설계한다.",
      "",
      "## 2. 선행연구",
      "",
      "- 검색은 두 방향으로 한다: 위로(내가 쓰는 방법의 원출처) 아래로(그 방법을 비판한 후속). **후속 비판을 안 읽고 쓰면 리뷰어가 대신 읽어준다.**",
      "- 가장 가까운 선행연구 3편은 방법, 데이터, 결론을 표로 만들어 옆에 둔다. 차별점은 그 표의 빈칸이다.",
      "- \"겹치는가\"보다 \"겹치면 얼마나 남는가\"를 묻는다. 완전히 새로운 건 거의 없다. 남는 게 논문 한 편 크기인지가 판단 기준이다.",
      "- 표면이 비슷한 것과 본질이 같은 것은 다르다. 같은 지표를 써도 무엇을 검증했는지가 다르면 다른 연구다. 반대로 이름이 달라도 같은 걸 했으면 같은 연구다.",
      "- 성격이 다른 계열의 선행연구를 한 문단에 섞지 않는다. 내 연구가 어느 계열인지 흐려진다.",
      "",
      "## 3. 설계",
      "",
      "- **결과를 보기 전에 판정 규칙을 적는다.** 이게 자기기만을 막는 가장 값싼 장치다.",
      "- 확정할 주장은 하나로 줄인다. 확정 항목이 늘수록 각각이 약해진다. 나머지는 탐색으로 정직하게 표시한다.",
      "- 반증 조건을 명시한다. \"이 결과가 나오면 내 가설이 틀린 것\"을 못 쓰면 설계가 아직 닫히지 않았다.",
      "- 자유도를 세어본다. 전처리 방식, 임계값, 필터, 모델 변형. 각각이 결론을 흔들 수 있다면 **하나를 확정으로 박고 나머지는 민감도**로 돌린다.",
      "- 기준선은 강한 걸 고른다. 약한 기준선 대비 우위는 논문이 아니라 광고다.",
      "- 파일럿을 먼저 돌린다. 전체 설계를 1/10 규모로 끝까지 한 번 통과시키면 대부분의 설계 결함이 드러난다.",
      "",
      "## 4. 구현과 실행",
      "",
      "- **재현 가능성은 나중에 붙이는 게 아니라 처음부터 있는 것이다.** 시드, 버전, 설정, 환경을 고정하고 기록한다.",
      "- 임계값과 상수는 한 곳에 모은다. 흩어져 있으면 민감도 분석이 며칠짜리가 된다.",
      "- 결과와 그 결과를 만든 명령, 출력을 함께 남긴다. 손으로 옮긴 숫자는 반드시 언젠가 틀린다.",
      "- 중간 산출물을 버리지 않는다. 6개월 뒤 리뷰어 질문의 답은 대개 중간 산출물에 있다.",
      "- 코드를 믿기 전에 **알려진 답이 있는 입력**으로 통과시킨다. 정상 동작 확인 없이 나온 신기한 결과는 대부분 버그다.",
      "",
      "## 5. 추론",
      "",
      "- 유효표본수는 명목표본수보다 작다. 반복측정, 클러스터, 자기상관이 있으면 추론 단위를 그 수준으로 올린다.",
      "- **비교는 같은 공간, 같은 단위, 같은 잡음원에서 한다.** 잡음원을 작게 잡으면 없는 차이를 발견하게 된다.",
      "- \"차이가 없다\"와 \"차이를 검출할 수 없다\"는 다르다. 후자면 검출 한계를 함께 보고한다.",
      "- 지표가 실제로 재는 것 이상을 주장하지 않는다. 대부분의 과장은 여기서 나온다.",
      "- 절대값이 해석 가능한 지표는 드물다. 기준선, 상한, 하한 중 뭘 앵커로 쓸지 먼저 정한다.",
      "- 사후에 고른 것은 전부 사후라고 쓴다. 마진, 변형, 하위집단, 필터.",
      "",
      "## 6. 자기기만 방지",
      "",
      "- 기대와 다르면 **코드, 지표, 가설** 순으로 의심한다. 순서를 뒤집으면 확증편향이다.",
      "- 잘 나온 결과일수록 더 깐깐하게 본다. 포화된 수치는 성능이 아니라 변별력 상실인 경우가 많다.",
      "- 주기적으로 자기 연구를 적대적으로 감사한다. \"내가 리뷰어면 어디를 찌를까\"를 목록으로 쓰고, 각각에 답이 있는지 본다.",
      "- 부정적 결과를 결과 절에 넣는다. 숨기면 결론의 신뢰도 전체가 흔들린다.",
      "- 여러 번 논거로 쓴 수치일수록 원본과 대조한다. 반복이 정확성을 만들지 않는다.",
      "",
      "## 7. 쓰기",
      "",
      "- 서론에서 **무엇을 주장하지 않는지**를 먼저 정한다. 주장 범위가 좁을수록 방어가 쉽다.",
      "- 약점은 리뷰어보다 먼저 쓴다. 늦게 발견될수록 비싸다.",
      "- 개별 요소의 신규성을 주장하지 않는다. 결합, 적용 맥락, 검증 방식에 신규성을 둔다.",
      "- 한 절을 한 문장으로 요약 못 하면 그 절은 아직 정리가 안 됐다.",
      "- 그림 하나가 논문의 주장 하나를 담게 만든다. 그림을 먼저 그려보면 논리 구멍이 보인다.",
      "- 초고는 빨리 쓰고 오래 고친다. 완성된 생각을 기다려 쓰기 시작하면 영원히 안 쓴다.",
      "",
      "## 8. 사람과 시간",
      "",
      "- 혼자 3회 이상 방향을 뒤집었으면 더 생각해서 풀 문제가 아니다. **결정을 지도교수에게 올린다.**",
      "- 올릴 때는 표로 간다: 항목 / 현재 상태 / 왜 내가 못 정하는가 / 선택지와 각각의 대가.",
      "- 매주 한 번 묻는다. \"지금 작업이 어느 질문의 어느 주장을 지탱하는가.\" 답이 없으면 멈춘다.",
      "- 스코프 축소는 대개 옳은 선택이다. 하나를 끝까지 방어하는 게 셋을 얕게 걸치는 것보다 낫다.",
      "- 완결된 작은 결과 하나가 미완의 큰 구상보다 가치 있다. 축적은 완결된 단위로만 쌓인다.",
      "- 도구는 재사용을 전제로 만든다. 지금 프로젝트가 끝나도 남는 것이 실질적 자산이다.",
    ],

    // /home/memo/work.md -- the other half. Research is graded on being right;
    // a company is graded on effect, and the habits that carry over are few enough
    // to list.
    work: [
      "# 회사 생활 원칙",
      "",
      "연구실에서 회사로 넘어갈 때, 그리고 회사에서 계속할 때 주기적으로 볼 것.",
      "연구자, 엔지니어 직군 기준이다.",
      "",
      "## 0. 가장 큰 차이",
      "",
      "- 연구는 **옳음**으로 평가받고, 회사는 **영향**으로 평가받는다. 옳은데 아무도 안 쓰면 회사에서는 0이다.",
      "- 연구는 깊게 파는 게 미덕이고, 회사는 **적절한 깊이에서 멈추는 것**이 미덕이다. 언제 멈출지가 실력이다.",
      "- 연구는 혼자 끝낼 수 있고, 회사 일은 거의 혼자 안 끝난다. 남을 통해 일이 되게 하는 것이 업무의 절반이다.",
      "- 정답이 하나인 문제는 거의 없다. 제약(일정, 예산, 인력, 리스크) 안에서의 선택이 대부분이다.",
      "",
      "## 1. 일을 받을 때",
      "",
      "- **\"무엇을 만들까\"가 아니라 \"이게 풀리면 뭐가 달라지나\"를 먼저 묻는다.** 요청받은 해법이 최선이 아닌 경우가 흔하다.",
      "- 요구사항은 반드시 되풀이해서 확인한다. \"제가 이해한 건 A, B이고 C는 범위 밖입니다. 맞습니까.\" 이 한 줄이 몇 주를 아낀다.",
      "- 성공 기준과 마감을 처음에 합의한다. 나중에 정하면 남이 정한다.",
      "- 애매하면 물어본다. 물어보는 비용은 하루, 잘못 만드는 비용은 2주다. **신입일수록 이 계산을 반대로 한다.**",
      "- 못 하겠으면 빨리 말한다. 늦게 말할수록 선택지가 사라진다.",
      "",
      "## 2. 일을 할 때",
      "",
      "- **80%에서 한 번 보여준다.** 100%까지 혼자 가서 방향이 틀렸으면 전부 손해다. 중간 확인은 나약함이 아니라 리스크 관리다.",
      "- 가장 불확실한 부분을 먼저 친다. 쉬운 것부터 하면 진척은 보이지만 리스크는 그대로 남는다.",
      "- 두 번 이상 반복될 일은 자동화하거나 문서화한다. 세 번째부터 이익이다.",
      "- 완벽한 설계보다 **되돌릴 수 있는 결정**이 낫다. 되돌리기 어려운 결정만 시간을 들여 고민한다.",
      "- 남이 이어받을 수 있게 만든다. 내가 없으면 안 돌아가는 상태는 안정감이 아니라 족쇄다.",
      "- 기술 선택은 취향이 아니라 **팀이 유지할 수 있는가**로 정한다.",
      "",
      "## 3. 보고와 커뮤니케이션",
      "",
      "- **결론 먼저, 근거 나중.** 상사는 과정이 아니라 판단에 필요한 것을 원한다.",
      "- 보고 형식: 결론 / 근거 / 리스크 / 필요한 결정. 네 줄이면 대부분 충분하다.",
      "- 나쁜 소식은 빠르게, 담백하게. 포장하면 신뢰가 깎이고, 늦으면 두 배로 깎인다.",
      "- 문제만 들고 가지 않는다. 최소한 선택지 두 개와 각각의 대가를 붙인다.",
      "- **결정은 글로 남긴다.** 왜 그렇게 정했는지, 무엇을 포기했는지. 6개월 뒤 그 결정을 방어해야 하는 건 나다.",
      "- 회의 후 요약을 보낸다. 합의 내용을 문자로 만든 사람이 사실상 그 합의를 정의한다.",
      "- 모르면 모른다고 한다. 아는 척은 한 번 들키면 그 뒤 모든 말의 신뢰도가 내려간다.",
      "",
      "## 4. 사람",
      "",
      "- **선의를 기본값으로 둔다.** 대부분의 갈등은 악의가 아니라 정보 비대칭과 인센티브 차이에서 나온다.",
      "- 상대의 목표를 안다. 상사나 타팀이 무엇으로 평가받는지 알면 설득 방식이 정해진다.",
      "- 공개적으로 반박하지 않는다. 사실 정정도 자리를 가린다.",
      "- 크레딧은 넉넉하게 나눈다. 줄여서 얻는 것보다 나눠서 얻는 것이 크다.",
      "- 도움을 받으면 갚는다. 회사에서 통용되는 화폐는 신뢰다.",
      "- 싫은 사람과도 일이 되게 만든다. 좋아할 필요는 없고 예측 가능하기만 하면 된다.",
      "- **정치를 혐오하되 무시하지 않는다.** 누가 무엇을 결정하는지 아는 건 정치가 아니라 지도다.",
      "",
      "## 5. 평가와 커리어",
      "",
      "- 성과는 자동으로 보이지 않는다. 보이게 만드는 것도 일이다. 과장이 아니라 **정확한 가시화**다.",
      "- 분기마다 자기 성과를 한 줄씩 기록해둔다. 평가철에 기억으로 쓰면 반드시 손해 본다.",
      "- **숫자로 말할 수 있는 형태를 만든다.** 시간 단축, 비용 절감, 오류 감소, 매출 기여.",
      "- 시키는 일만 잘하면 좋은 실무자, 문제를 스스로 찾아 정의하면 그 위다. 승진은 대개 후자에서 갈린다.",
      "- 지금 자리에서 안 배우면 어디서도 안 배운다. 배울 게 정말 없어졌을 때가 움직일 때다.",
      "- 이직은 도망이 아니라 선택일 때 한다. 도망으로 하면 같은 문제를 다시 만난다.",
      "- 회사 밖에서도 통하는 능력을 축적한다. 사내 전용 지식만 쌓이면 협상력이 사라진다.",
      "",
      "## 6. 자기 보호",
      "",
      "- **과로는 성실함이 아니라 계획 실패의 결과인 경우가 많다.** 반복되면 원인을 위에 보고한다.",
      "- 거절은 기술이다. \"지금 A를 하고 있는데 B가 더 급하면 A를 미루면 됩니까.\" 우선순위를 상대에게 돌려준다.",
      "- 회사는 가족이 아니다. 좋은 동료는 있어도 회사 자체는 계약 상대다. 헌신과 종속을 구분한다.",
      "- 번아웃은 갑자기 안 온다. 흥미 상실, 냉소, 수면 변화가 먼저 온다. 신호를 알아두고, 오래 지속되면 쉬거나 전문가를 찾는다.",
      "- 기록을 남긴다. 부당한 일이 생겼을 때 유일하게 나를 지키는 건 문서다.",
      "- 건강과 관계는 회복이 가장 느린 자산이다. 나중에 챙기면 늦다.",
      "",
      "## 7. 연구 습관 중 그대로 가져갈 것",
      "",
      "- 결론 내기 전에 판정 기준 정하기",
      "- 기대와 다르면 코드, 지표, 가설 순으로 의심하기",
      "- 약점을 남이 지적하기 전에 내가 먼저 말하기",
      "- 결정과 근거를 기록으로 남기기",
      "- 혼자 세 번 뒤집었으면 위로 올리기",
    ],

    // /home/memo/social.md -- half of it is mail, because in practice most of the
    // impression is decided in writing.
    social: [
      "# 사회생활 원칙",
      "",
      "한국 직장, 학계 기준. 메일 파트가 절반이다.",
      "실무에서 인상은 대부분 글로 결정된다.",
      "",
      "## 1. 기본",
      "",
      "- 사회생활의 대부분은 **예측 가능성**이다. 뛰어남보다 \"이 사람은 말하면 되고, 약속을 지킨다\"가 강하다.",
      "- 작은 약속을 지킨다. 큰 신뢰는 큰 사건이 아니라 작은 것의 누적으로 생긴다.",
      "- 응답 속도가 성실함의 대리 지표로 읽힌다. 당장 못 해도 **\"확인했습니다, 언제까지 회신드리겠습니다\"** 한 줄은 즉시 보낸다.",
      "- 처음 만나는 사람에게는 반 톤 더 격식을 차린다. 낮추는 건 쉽고 올리는 건 어렵다.",
      "- 사람 이름과 직함을 정확히 쓴다. 틀리면 그 자체로 메시지다.",
      "",
      "## 2. 호칭과 말",
      "",
      "- 확실하지 않으면 **\"○○○ 님\"** 이 가장 안전하다. 직함을 알면 직함이 낫다(교수님, 팀장님, 박사님).",
      "- 나이나 기수 서열을 먼저 재려 들지 않는다. 상대가 먼저 정리해주는 걸 기다리는 편이 낫다.",
      "- 이메일과 메신저의 존댓말 수위는 **상대가 쓰는 수위에 맞춘다.** 상대가 낮추면 반 단계만 따라 낮춘다.",
      "- \"수고하셨습니다\"는 아랫사람이나 동급에, 윗사람에게는 \"고생 많으셨습니다\" 또는 \"감사합니다\"가 무난하다.",
      "- 단정적 표현을 줄인다. \"아닙니다\" 대신 \"제가 알기로는 조금 다른데, 확인해보겠습니다\".",
      "",
      "## 3. 메일",
      "",
      "### 3.1 원칙",
      "",
      "- **두괄식.** 첫 문단에 용건과 요청을 다 넣는다. 배경은 그 뒤다.",
      "- 메일 하나에 **용건 하나**. 두 개면 두 통으로 나눈다. 섞으면 하나만 처리된다.",
      "- 요청에는 반드시 **누가 / 무엇을 / 언제까지**가 있어야 한다. 셋 중 하나라도 빠지면 안 움직인다.",
      "- 상대가 스크롤 없이 읽을 분량을 목표로 한다. 길면 요약을 맨 위에 붙인다.",
      "- 감정이 실린 메일은 **쓰고 나서 하룻밤 재운다.** 보낸 메일은 회수가 안 된다.",
      "- 기록으로 남는다는 걸 항상 전제한다. 유출돼도 곤란하지 않을 문장만 쓴다.",
      "",
      "### 3.2 제목",
      "",
      "- 용건이 제목만으로 파악돼야 한다. `[소속/과제] 핵심 용건 (요청 기한)` 형식이 무난하다.",
      "- 나쁜 예: `안녕하세요`, `문의드립니다`, `자료`",
      "- 좋은 예: `[경북대 STLAB] 3차 중간보고서 검토 요청 (~8/28)`",
      "- 회신 시 제목을 함부로 바꾸지 않는다. 스레드가 끊긴다.",
      "- 급하면 `[긴급]`을 쓰되 진짜 긴급할 때만. 남용하면 다음부터 안 읽힌다.",
      "",
      "### 3.3 구조",
      "",
      "```",
      "받는사람 호칭",
      "  안녕하십니까, ○○○ 님.",
      "  [소속] [이름]입니다.",
      "",
      "용건 (1~2문장, 두괄식)",
      "  ○○ 건으로 △△를 요청드리고자 연락드립니다.",
      "",
      "배경과 상세 (필요한 만큼만, 항목화)",
      "",
      "요청 사항 (누가/무엇을/언제까지)",
      "  - 회신 기한:",
      "  - 첨부:",
      "",
      "마무리",
      "  확인 부탁드립니다. 감사합니다.",
      "",
      "서명 (이름 / 소속 / 직함 / 연락처)",
      "```",
      "",
      "### 3.4 참조와 숨은참조",
      "",
      "- **CC는 \"알고 계시라\"**, TO는 \"당신이 처리해야 한다\". 이 구분을 흐리면 아무도 안 움직인다.",
      "- CC에 사람을 늘리는 건 압박으로 읽힌다. 필요한 사람만 넣는다. 특히 **상대의 상사를 CC에 넣는 것은 에스컬레이션 신호**다. 의도한 게 아니면 넣지 않는다.",
      "- 여러 외부인에게 동시에 보낼 때는 BCC를 쓴다. TO에 주소를 늘어놓으면 개인정보 사고다.",
      "- 전체답장 전에 수신자 목록을 본다. 실수 중 가장 비싼 축이다.",
      "",
      "### 3.5 회신",
      "",
      "- 24시간 내 회신을 기본으로 한다. 못 하면 대기 메일이라도 보낸다.",
      "- 인용 답변이 필요하면 항목별로 나눠 답한다. 상대 질문 3개면 답도 3개다.",
      "- \"확인했습니다\"만 보내는 건 상대가 기다리는 상황에서 의미가 있다. 아니면 노이즈다.",
      "- 첨부를 언급했으면 **보내기 전에 첨부를 확인한다.** 가장 흔한 실수다.",
      "",
      "### 3.6 예문: 지연이나 거절",
      "",
      "```",
      "제목: RE: 3차 중간보고서 검토 요청 - 일정 조정 문의",
      "",
      "안녕하십니까, ○○○ 님.",
      "",
      "요청주신 검토 건, 결론부터 말씀드리면 8/28까지는 어렵고 9/2까지 가능합니다.",
      "",
      "현재 △△ 실험 재수행이 8/30까지 예정되어 있어,",
      "그 결과가 반영되지 않은 상태로 드리면 재검토가 한 번 더 필요할 것으로 보입니다.",
      "",
      "두 가지 중 편하신 쪽으로 정해주시면 맞추겠습니다.",
      "1) 9/2에 실험 반영본 일괄 전달",
      "2) 8/28에 현재분 우선 전달, 실험 부분만 9/2 추가",
      "",
      "감사합니다.",
      "```",
      "",
      "### 3.7 예문: 실수 정정",
      "",
      "```",
      "제목: [정정] 3차 중간보고서 - 표 2 수치 오류",
      "",
      "앞서 보내드린 보고서의 표 2에 오류가 있어 정정본을 첨부드립니다.",
      "",
      "- 오류: 표 2 recall 값 0.007, 정확한 값 0.014",
      "- 원인: 집계 스크립트의 단위 변환 누락",
      "- 영향: 표 2 및 4.2절 서술. 결론은 변동 없음",
      "- 조치: 해당 스크립트에 검증 테스트 추가",
      "",
      "혼선 드려 죄송합니다. 첨부본으로 대체 부탁드립니다.",
      "```",
      "",
      "> 정정 메일의 요령: **사과는 짧게, 사실과 원인과 영향과 조치는 명확하게.**",
      "> 길게 사과할수록 문제가 커 보인다.",
      "",
      "## 4. 메신저와 전화",
      "",
      "- 메신저에서 `안녕하세요`만 보내고 기다리지 않는다. 인사와 용건을 한 번에 보낸다.",
      "- 긴 논의는 메신저에서 끌지 말고 메일이나 통화로 옮긴다. 대신 **결론은 다시 글로 남긴다.**",
      "- 업무 시간 외 메시지는 예약 발송을 쓴다. 받는 사람 입장에서는 요구로 읽힌다.",
      "- 전화 전에 메시지로 가능 여부를 묻는 게 요즘 기본이다. 급하면 전화하고 사후에 요약을 남긴다.",
      "- 전화로 정한 것은 반드시 글로 확인한다. \"말씀 주신 내용 정리하면 A, B입니다. 맞습니까.\"",
      "",
      "## 5. 부탁과 거절",
      "",
      "- 부탁할 때는 **상대의 부담을 먼저 계산해서 말한다.** \"30분 정도 걸릴 것 같습니다\"가 있고 없고의 차이가 크다.",
      "- 대안을 함께 준다. \"어려우시면 ○○ 쪽에 문의해도 괜찮습니다.\"",
      "- 거절은 빠르게. 애매하게 끌면 상대의 대안이 사라진다.",
      "- 거절 공식: **감사, 불가 사유(간단히), 대안.** 사유를 길게 늘어놓으면 변명으로 읽힌다.",
      "- 거절해도 관계는 유지된다. 오히려 애매한 수락 후의 미이행이 관계를 끊는다.",
      "",
      "## 6. 실수했을 때",
      "",
      "- 빨리, 짧게, 조치와 함께. 이 세 개다.",
      "- 변명과 설명을 구분한다. 원인 설명은 필요하고, 책임 회피는 티가 난다.",
      "- 같은 실수를 두 번 하지 않게 만든 장치를 함께 말한다. 그게 신뢰 회복의 실질이다.",
      "- 남의 실수는 공개적으로 짚지 않는다. 개인적으로, 사실만.",
      "",
      "## 7. 모임, 식사, 경조사",
      "",
      "- 참석 여부는 빨리 답한다. 주최자 입장에서 미정이 가장 곤란하다.",
      "- 술은 안 마셔도 된다. **\"제가 술을 잘 못합니다\"** 한 번 말해두면 대개 끝난다. 계속 강권하는 자리는 기억해뒀다가 다음부터 거리를 둔다.",
      "- 자리에서 나온 뒷담화에 동조하지 않는다. 옮기지 않는 사람이라는 평판이 길게 남는다.",
      "- 경조사는 챙기면 오래 기억된다. 특히 조사가 그렇다. 액수보다 참석이 크다.",
      "- 먼저 일어날 때는 조용히, 주최자에게만 인사하고 나온다.",
      "",
      "## 8. 관계 유지",
      "",
      "- 필요할 때만 연락하면 필요할 때 안 통한다. 부탁 없는 연락을 가끔 한다.",
      "- 받은 도움은 결과를 알려준다. \"말씀해주신 방향으로 진행해서 이렇게 됐습니다.\" 이게 가장 좋은 답례다.",
      "- 좋은 소식은 나누고, 남의 좋은 소식에는 반응한다. 축하 한 줄의 비용 대비 효과가 크다.",
      "- 연락처는 헤어질 때 정리해둔다. 나중에 찾으면 이미 늦다.",
      "",
      "## 9. 선 긋기",
      "",
      "- 사생활은 묻는 만큼만 답한다. 답하기 싫으면 웃으며 화제를 돌려도 무례가 아니다.",
      "- 무례한 말에는 그 자리에서 짧게 표시한다. \"그 표현은 좀 그렇습니다.\" 참으면 반복된다.",
      "- 심한 경우는 기록한다. 날짜, 발언, 목격자. 감정 대응보다 기록이 강하다.",
      "- **호의와 의무를 구분한다.** 계속 받기만 하는 관계도, 계속 주기만 하는 관계도 오래 못 간다.",
      "- 모든 사람에게 좋은 평가를 받을 수는 없다. 목표는 호감이 아니라 **신뢰**다.",
    ],

    // /home/jeongin/.lab/grad.md -- the lab as an organisation, as opposed to
    // principles.md, which is the research itself.
    grad: [
      "# 연구실 생활 원칙",
      "",
      "한국 이공계 대학원 기준. 연구 방법론은 `principles.md`,",
      "메일 형식은 `/home/memo/social.md` 3절을 본다.",
      "여기는 **연구실이라는 조직**에서 살아남고 축적하는 법이다.",
      "",
      "## 1. 대학원의 구조",
      "",
      "- 대학원생은 **학생이자 노동자이자 공동연구자**다. 세 역할의 비중이 상황마다 바뀌고, 그 혼선이 대부분의 스트레스 원인이다. 지금 어느 역할로 요청받고 있는지 구분하면 대응이 쉬워진다.",
      "- 학위는 **연구 능력의 증명**이지 연구의 완성이 아니다. 완벽한 논문을 목표로 하면 졸업이 늦어진다.",
      "- 시간은 무제한이 아니다. 학기 수, 인건비, 과제 기간이 다 유한하다. **역산으로 계획한다.**",
      "- 지도교수와의 관계가 대학원 생활의 만족도를 가장 크게 결정한다. 이 관계에 시간을 투자하는 게 합리적이다.",
      "",
      "## 2. 지도교수",
      "",
      "- **교수는 바쁘다. 정보 요약의 책임은 학생에게 있다.** 상황 설명 10분보다 정리된 한 장이 낫다.",
      "- 미팅에 갈 때는 세 가지를 준비한다: **지난주 한 것 / 막힌 것 / 결정이 필요한 것.** 마지막 항목이 핵심이다.",
      "- 결정을 올릴 때는 표로 간다. 항목 / 현재 상태 / 선택지 / 각각의 대가 / 내 추천. **\"어떻게 할까요\"만 들고 가지 않는다.**",
      "- 혼자 3회 이상 방향을 뒤집었으면 더 생각해서 풀 문제가 아니다. 올린다.",
      "- 진척이 없는 주에도 보고한다. 침묵은 문제 은폐로 읽힌다. \"이번 주는 A를 시도했고 실패했습니다, 원인은 B로 봅니다\"가 정상적인 보고다.",
      "- 교수의 지시가 바뀌면 화내지 말고 기록한다. 방향 전환은 흔하다. **기록이 있으면 다음 전환 때 근거가 된다.**",
      "- 반대 의견은 데이터로 낸다. \"그건 아닌 것 같습니다\"가 아니라 \"그 가정으로 돌렸더니 이 결과가 나왔습니다\".",
      "- 교수도 틀린다. 다만 틀렸다는 걸 증명하는 비용이 학생 쪽에 있다는 걸 감안한다.",
      "",
      "## 3. 미팅과 발표",
      "",
      "- 슬라이드는 결론부터. 실험 과정을 시간 순으로 나열하면 아무도 안 따라온다.",
      "- **그림 한 장으로 설명 못 하는 결과는 아직 이해 못 한 결과다.**",
      "- 모르는 질문에는 \"확인해서 회신드리겠습니다\"라고 한다. 지어내면 그다음 모든 답의 신뢰가 내려간다.",
      "- 랩 세미나에서 남의 발표에 질문한다. 질문하는 사람으로 인식되는 것이 장기적으로 이익이다.",
      "- 미팅 후 결정 사항을 스스로 정리해 남긴다. 몇 달 뒤 \"그때 그렇게 정했지\" 논쟁의 유일한 근거다.",
      "",
      "## 4. 과제와 행정",
      "",
      "- 정부과제는 **연구와 별개의 일정**을 가진다. 연차보고서, 실적 정리, 증빙이 갑자기 2주를 먹는다. 미리 캘린더에 박는다.",
      "- 실적(논문, 특허, SW등록)은 과제 평가 항목이다. 내 연구가 어느 실적 칸에 들어가는지 알고 있으면 우선순위가 명확해진다.",
      "- 행정 요청은 빨리 처리한다. 미루면 남의 일정까지 끈다. 이걸로 얻는 평판이 의외로 크다.",
      "- 영수증, 출장, 구매는 규정이 까다롭다. 애매하면 먼저 물어본다. 사후 처리는 거의 안 된다.",
      "- **인건비, 참여율, 학생 신분 조건을 스스로 알아둔다.** 남이 챙겨줄 것으로 기대하지 않는다.",
      "",
      "## 5. 논문과 저자권",
      "",
      "- 저자 순서와 교신저자는 **일을 시작하기 전에** 이야기한다. 끝나고 꺼내면 갈등이 된다.",
      "- 기여의 형태를 기록한다. 아이디어, 구현, 실험, 집필, 데이터. 나중 논의의 근거가 된다.",
      "- 남의 코드나 데이터를 쓰면 명시한다. 랩 내부라도 마찬가지다.",
      "- 학회 마감은 역산해서 잡는다. 실험 완료, 초고, 지도교수 검토 2주, 수정, 제출. **검토 2주는 압축이 안 된다.**",
      "- 리젝은 표준이다. 리뷰를 하루 재웠다가 항목별로 정리하고, 반영과 미반영을 표로 만든다.",
      "- 졸업 요건(논문 편수, 학회, 심사 일정)을 입학 초에 확인하고 매 학기 점검한다. 마지막 학기에 발견하면 늦다.",
      "",
      "## 6. 랩 안에서의 관계",
      "",
      "- 선배에게 묻는 게 가장 빠르다. 다만 **찾아본 흔적을 보여주고 묻는다.** \"A를 해봤는데 B에서 막혔습니다\"와 \"이거 어떻게 해요\"는 다르게 대접받는다.",
      "- 받은 만큼 후배에게 돌려준다. 랩의 지식은 이 순환으로만 유지된다.",
      "- 후배를 가르치면 자기 이해가 정리된다. 시간 낭비가 아니다.",
      "- 랩 잡무는 공평하게 나뉘지 않는다. 티 안 나는 일을 계속 하고 있으면 한 번은 말한다. 말 안 하면 계속 간다.",
      "- 랩 내 갈등은 대개 자원(장비, 데이터, 저자권, 교수의 시간) 문제다. 인성 문제로 프레임하면 안 풀린다.",
      "- 뒷담화에 동조하지 않는다. 좁은 사회고 반드시 돌아온다.",
      "",
      "## 7. 축적",
      "",
      "- **모든 것을 리포에 넣는다.** 코드, 설정, 노트, 결정 기록. 흩어진 지식은 졸업과 함께 사라진다.",
      "- 실험은 실행 명령과 출력을 함께 남긴다. 손으로 옮긴 숫자는 언젠가 틀린다.",
      "- 주간 로그를 남긴다. 5줄이면 된다. 연차보고서, 학위논문 서론, 이력서가 전부 여기서 나온다.",
      "- 읽은 논문은 3줄로 정리한다: 무엇을 했나 / 어떻게 검증했나 / 내 연구와의 관계. 이 습관이 서베이를 대신한다.",
      "- **졸업 후에도 남는 자산**을 의식적으로 만든다. 재사용 가능한 도구, 공개 가능한 코드, 발표 경험, 사람.",
      "",
      "## 8. 시간과 리듬",
      "",
      "- 대학원은 마감이 드물어서 스스로 만들지 않으면 시간이 녹는다. **주 단위 목표를 스스로 건다.**",
      "- 하루 중 머리가 가장 잘 도는 시간대를 연구에 쓴다. 그 시간에 메일이나 행정을 하면 손해다.",
      "- 오래 앉아 있는 것과 진척은 무관하다. 랩에 있는 시간이 아니라 **완결된 단위**로 자기 진도를 잰다.",
      "- 막히면 자리를 뜬다. 같은 화면을 세 시간 보는 건 대개 소득이 없다.",
      "- 완결된 작은 결과 하나가 미완의 큰 구상보다 가치 있다. 축적은 완결 단위로만 쌓인다.",
      "",
      "## 9. 자기 관리",
      "",
      "- 대학원생의 불안은 대부분 **진척이 안 보여서** 온다. 로그를 남기면 실제로 줄어든다. 안 보였을 뿐 하고 있었던 경우가 많다.",
      "- 비교는 무의미하다. 옆 사람의 주제, 데이터, 운, 지도 방식이 전부 다르다.",
      "- 연구 실패와 자기 가치를 분리한다. 실험이 안 된 건 실험이 안 된 것이다.",
      "- 흥미 상실, 냉소, 수면이나 식사 변화가 오래 이어지면 혼자 버티지 말고 **학교 상담센터나 전문가를 찾는다.** 대부분의 대학에 무료로 있고, 이용하는 게 정상적인 선택이다.",
      "- 랩 밖의 관계와 활동을 하나는 유지한다. 정체성이 연구 하나에만 걸려 있으면 연구가 흔들릴 때 같이 흔들린다.",
      "- 명백히 부당한 상황(폭언, 사적 지시, 인건비 문제)은 기록하고 학내 인권센터나 대학원총학 등 공식 창구를 확인한다. 참는 것이 해결이 아니다.",
      "",
      "## 10. 진로",
      "",
      "- 졸업 1년 전부터 방향(취업, 박사, 창업)을 정하고 역산한다.",
      "- 학회는 발표하러만 가는 곳이 아니다. **사람을 만나러 간다.** 관심 있는 발표자에게 질문하고 명함을 남긴다.",
      "- 인턴이나 산학과제는 가능하면 한 번 한다. 회사와 학교의 일하는 방식 차이를 미리 겪는 값이 크다.",
      "- 이력서는 매 학기 갱신한다. 나중에 몰아서 쓰면 반드시 빠뜨린다.",
      "- 지도교수와 진로 이야기를 미루지 않는다. 추천서나 소개가 필요한 시점에 처음 꺼내면 늦다.",
    ],

  },


  // ── Text shown in intros (Easy mode callout + terminal `about` command) ──
  intro: {
    about: {  // Easy mode callout box (under the title)
      ko: {
        primary: "안녕하세요. 경북대학교 컴퓨터학부에서 소프트웨어 테스팅을 공부하고 있어요.",
        secondary: "LLM 기반 테스트 생성, SIL 검증 환경, 산업 공정 데이터 예측 모델링에 관심이 있습니다.",
      },
      en: {
        primary: "Hi, I study software testing at Kyungpook National University.",
        secondary: "LLM-based test generation, software-in-the-loop verification environments, and predictive modelling on industrial process data.",
      },
    },
    tagline: {
      ko: {
        primary: "LLM을 활용한 소프트웨어 테스트 자동화와 신뢰성 검증을 연구합니다.",
        secondary: "AI와 소프트웨어가 상호 보완적으로 작동하는 방법을 고민합니다.",
      },
      en: {
        primary: "My research focuses on software test automation and reliability verification using LLMs.",
        secondary: "Exploring ways AI and software can complement each other.",
      },
    },
  },

  // ── `fortune` easter-egg pool ──
  fortunes: {
    ko: [
      "테스트 없는 코드는 레거시다. - Michael Feathers",
      "버그는 특성이 아니다. 특성이 버그일 뿐.",
      "커버리지 100%는 방어선이지 승리선이 아니다.",
      "오라클이 약하면 테스트는 그냥 실행기다.",
      "LLM 은 답을 아는 친구가 아니라, 자신만만한 인턴이다.",
      "느린 테스트는 결국 안 돌리는 테스트가 된다.",
      "플레이크는 잡는 게 아니라 제거하는 것이다.",
      "가장 좋은 회귀 테스트는, 회귀를 재현하는 테스트이다.",
    ],
    en: [
      "Code without tests is legacy. -- Michael Feathers",
      "A bug is not a feature. A feature is a bug with marketing.",
      "100% coverage is a floor, not a ceiling.",
      "A weak oracle turns tests into runners.",
      "LLMs aren't the friend who knows -- they're the confident intern.",
      "A slow test is a test that never runs.",
      "You don't catch flakes. You eliminate them.",
      "The best regression test is one that reproduces the regression.",
    ],
  },
};
